
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { useSession, signIn, signOut } from "next-auth/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Feedonymous",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg", // public path
  },
  manifest:"/manifest.webmanifest"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { data: session } = useSession();
  // const username = session?.user?.name ? session.user.name.split(" ")[0] : "Guest";
  return (
    <html lang="en">
      {/* <script src="https://checkout.razorpay.com/v1/checkout.js"></script> */}
      <AuthProvider>
        <body className={inter.className}>
          {children}
          {/* <Navbar username={username} /> */}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
